// Code generated by mockery v2.36.1. DO NOT EDIT.

package mocks

import (
	models "job-services/internal/models"

	mock "github.com/stretchr/testify/mock"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// AddDataToDB provides a mock function with given fields: transactions
func (_m *Service) AddDataToDB(transactions []*models.TransactionModel) error {
	ret := _m.Called(transactions)

	var r0 error
	if rf, ok := ret.Get(0).(func([]*models.TransactionModel) error); ok {
		r0 = rf(transactions)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
